# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a3f60c433467a2bceb56fd5678a1de9d1cb7ff103507b098c18a153b4c8b17f1f78ac1187c222bd44baf98c4aa4cbe967d253ca3bfc02bdbd61e9db870a6c3

test:
  secret_key_base: 3f94e0e7556968ee99df845e163cd9786542cb51d4d6c2e1e31b21fd289be5dc24ed8c219a87adfc11fbcdad648784e3ed6902f01ced41dab587e3fbbcf90287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
